export const FETCH_TEST_DATA = "FETCH_TEST_DATA";
export const FETCH_ENV_DATA = "FETCH_ENV_DATA";
export const FETCH_ENV_TEST_DATA = "FETCH_ENV_TEST_DATA";

export const TEST_DATA_LOADED = "TEST_DATA_LOADED";
export const ENV_DATA_LOADED = "ENV_DATA_LOADED";
export const ENV_TEST_DATA_LOADED = "ENV_TEST_DATA_LOADED";

export const ERROR_FETCH_TEST_DATA = "ERROR_FETCH_TEST_DATA";